[project]
name = "python-web-data-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wei-Cheng Chen", email = "3331363@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
python-web-data-automation = "python_web_data_automation:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
